export type Product = {
  id: string;
  name: string;
  price: number;
  category: string;
  brand: string;
  rating: number;
  badge?: string;
  verified?: boolean;
  description: string;
  specs: { label: string; value: string }[];
  unit: string;
};

export const filterCategories = [
  "الخرسانات والإسمنت",
  "معدات التسليح",
  "السيراميك والبلاط",
  "الدهانات والعوازل",
  "أدوات البناء",
  "السلامة المهنية",
  "السباكة والصرف",
  "الطاقة الشمسية",
];

export const brands = [
  "اليمامة",
  "حديد الراجحي",
  "جوتن",
  "نشاء",
  "هوندا",
  "بترو ست",
  "3M",
  "أسمنت اليمن",
  "ستانلي",
  "بوش",
  "ديوالت",
  "سيكا",
  "RAK سيراميك",
  "بورسلانوزا",
  "السعودية للسيراميك",
  "JA Solar",
  "Pylontech",
  "Deye",
];

export const products: Product[] = [
  {
    id: "p1",
    name: "إسمنت بورتلاندي 50 كجم",
    price: 28,
    category: "الخرسانات والإسمنت",
    brand: "اليمامة",
    rating: 4.8,
    badge: "الأكثر مبيعاً",
    verified: true,
    unit: "كيس",
    description:
      "إسمنت بورتلاندي عادي مطابق للمواصفات السعودية، مناسب لجميع أعمال الخرسانة المسلحة والبناء العام.",
    specs: [
      { label: "الوزن", value: "50 كجم" },
      { label: "النوع", value: "بورتلاندي عادي CEM I" },
      { label: "قوة التحمل", value: "42.5 ميجا باسكال" },
      { label: "بلد المنشأ", value: "السعودية" },
    ],
  },
  {
    id: "p2",
    name: "حديد تسليح مبروم 12 مم",
    price: 65,
    category: "معدات التسليح",
    brand: "حديد الراجحي",
    rating: 4.7,
    unit: "متر",
    description: "حديد تسليح عالي الجودة، مبروم بمواصفات هندسية تضمن المتانة والثبات في الإنشاءات.",
    specs: [
      { label: "القطر", value: "12 مم" },
      { label: "الطول", value: "12 متر" },
      { label: "الدرجة", value: "B500B" },
      { label: "الوزن/متر", value: "0.888 كجم" },
    ],
  },
  {
    id: "p3",
    name: "دهان أكريليك داخلي 18 لتر",
    price: 320,
    category: "الدهانات والعوازل",
    brand: "جوتن",
    rating: 4.9,
    badge: "جودة عالية",
    verified: true,
    unit: "جالون",
    description: "دهان أكريليك مائي للأسطح الداخلية، خالٍ من الروائح ويوفر تغطية ممتازة وثبات للون.",
    specs: [
      { label: "الحجم", value: "18 لتر" },
      { label: "التغطية", value: "12-14 م²/لتر" },
      { label: "وقت الجفاف", value: "30 دقيقة" },
      { label: "اللمعان", value: "مطفي" },
    ],
  },
  {
    id: "p4",
    name: "عازل حراري فوم 5 سم",
    price: 180,
    category: "الدهانات والعوازل",
    brand: "نشاء",
    rating: 4.6,
    unit: "لوح",
    description: "ألواح عازلة حرارياً من البولي يوريثان، توفر عزلاً ممتازاً للأسقف والجدران.",
    specs: [
      { label: "السماكة", value: "5 سم" },
      { label: "المقاس", value: "120×60 سم" },
      { label: "الكثافة", value: "35 كجم/م³" },
      { label: "معامل التوصيل", value: "0.024 W/m.K" },
    ],
  },
  {
    id: "p5",
    name: "خلاطة خرسانة 350 لتر",
    price: 4200,
    category: "أدوات البناء",
    brand: "هوندا",
    rating: 4.5,
    verified: true,
    unit: "قطعة",
    description: "خلاطة خرسانة احترافية بمحرك بنزين قوي، مناسبة لمواقع البناء المتوسطة والكبيرة.",
    specs: [
      { label: "السعة", value: "350 لتر" },
      { label: "المحرك", value: "بنزين 5.5 حصان" },
      { label: "الوزن", value: "180 كجم" },
      { label: "الضمان", value: "سنتان" },
    ],
  },
  {
    id: "p6",
    name: "أنابيب PPR 25 مم - 4م",
    price: 45,
    category: "السباكة والصرف",
    brand: "بترو ست",
    rating: 4.7,
    unit: "أنبوب",
    description: "أنابيب بولي بروبلين مقاومة للحرارة العالية، مثالية لشبكات المياه الباردة والساخنة.",
    specs: [
      { label: "القطر", value: "25 مم" },
      { label: "الطول", value: "4 متر" },
      { label: "الضغط", value: "PN 20" },
      { label: "درجة الحرارة", value: "حتى 95°م" },
    ],
  },
  {
    id: "p7",
    name: "خوذة سلامة مع حزام",
    price: 75,
    category: "السلامة المهنية",
    brand: "3M",
    rating: 4.8,
    unit: "قطعة",
    description: "خوذة سلامة احترافية مع حزام رأس قابل للتعديل، معتمدة دولياً لحماية العمال.",
    specs: [
      { label: "المادة", value: "ABS عالي الكثافة" },
      { label: "الوزن", value: "380 جرام" },
      { label: "المعيار", value: "EN 397" },
      { label: "الألوان", value: "أصفر، أبيض، أحمر" },
    ],
  },
  {
    id: "p8",
    name: "خرسانة جاهزة - متر مكعب",
    price: 285,
    category: "الخرسانات والإسمنت",
    brand: "أسمنت اليمن",
    rating: 4.6,
    unit: "م³",
    description: "خرسانة جاهزة بمواصفات هندسية محددة، يتم توريدها للموقع بسيارات الخلط الحديثة.",
    specs: [
      { label: "الدرجة", value: "C30/37" },
      { label: "الانضغاط", value: "30 ميجا" },
      { label: "السقوط", value: "10±2 سم" },
      { label: "وقت التوريد", value: "خلال 4 ساعات" },
    ],
  },
  {
    id: "p9",
    name: "مفتاح ربط متعدد المقاسات",
    price: 95,
    category: "أدوات البناء",
    brand: "ستانلي",
    rating: 4.7,
    badge: "خصم 15%",
    unit: "طقم",
    description: "طقم مفاتيح ربط احترافي متعدد المقاسات، مصنوع من الكروم فاناديوم عالي القوة.",
    specs: [
      { label: "عدد القطع", value: "12 قطعة" },
      { label: "المقاسات", value: "8-22 مم" },
      { label: "المادة", value: "Cr-V Steel" },
      { label: "الضمان", value: "مدى الحياة" },
    ],
  },
  {
    id: "p10",
    name: "مثقاب كهربائي 18 فولت",
    price: 580,
    category: "أدوات البناء",
    brand: "بوش",
    rating: 4.9,
    badge: "جديد",
    verified: true,
    unit: "قطعة",
    description: "مثقاب لاسلكي احترافي ببطارية ليثيوم، يدعم الثقب والربط في الخشب والمعدن والخرسانة.",
    specs: [
      { label: "الجهد", value: "18 فولت" },
      { label: "البطارية", value: "ليثيوم 4Ah" },
      { label: "العزم", value: "60 نيوتن.متر" },
      { label: "الضمان", value: "3 سنوات" },
    ],
  },
  {
    id: "p11",
    name: "أحذية سلامة جلدية",
    price: 220,
    category: "السلامة المهنية",
    brand: "3M",
    rating: 4.6,
    unit: "زوج",
    description: "أحذية سلامة بمقدمة معدنية ونعل مقاوم للانزلاق، مريحة للاستخدام الطويل.",
    specs: [
      { label: "المادة", value: "جلد طبيعي" },
      { label: "المقدمة", value: "فولاذ معدني" },
      { label: "النعل", value: "مطاط مقاوم" },
      { label: "المعيار", value: "EN ISO 20345" },
    ],
  },
  {
    id: "p12",
    name: "مونة لاصق سيراميك 25 كجم",
    price: 55,
    category: "الخرسانات والإسمنت",
    brand: "سيكا",
    rating: 4.7,
    unit: "كيس",
    description: "مونة لاصقة عالية الأداء لتثبيت السيراميك والبورسلين على جميع الأسطح.",
    specs: [
      { label: "الوزن", value: "25 كجم" },
      { label: "وقت الفتح", value: "20 دقيقة" },
      { label: "قوة اللصق", value: "1.5 N/mm²" },
      { label: "اللون", value: "رمادي" },
    ],
  },
  {
    id: "p13",
    name: "حديد تسليح 16 مم",
    price: 110,
    category: "معدات التسليح",
    brand: "حديد الراجحي",
    rating: 4.8,
    unit: "متر",
    description: "حديد تسليح بقطر 16 مم للأعمال الإنشائية الثقيلة والأعمدة الحاملة.",
    specs: [
      { label: "القطر", value: "16 مم" },
      { label: "الطول", value: "12 متر" },
      { label: "الدرجة", value: "B500B" },
      { label: "الوزن/متر", value: "1.578 كجم" },
    ],
  },
  {
    id: "p14",
    name: "دهان خارجي مقاوم للعوامل الجوية",
    price: 410,
    category: "الدهانات والعوازل",
    brand: "جوتن",
    rating: 4.8,
    badge: "موصى به",
    verified: true,
    unit: "جالون",
    description: "دهان خارجي مقاوم للأشعة فوق البنفسجية والأمطار، يحافظ على لمعانه لسنوات.",
    specs: [
      { label: "الحجم", value: "18 لتر" },
      { label: "التغطية", value: "10-12 م²/لتر" },
      { label: "العمر", value: "10 سنوات" },
      { label: "اللمعان", value: "نصف لامع" },
    ],
  },
  {
    id: "p15",
    name: "منشار دائري 1500 وات",
    price: 720,
    category: "أدوات البناء",
    brand: "ديوالت",
    rating: 4.7,
    unit: "قطعة",
    description: "منشار دائري كهربائي قوي للقطع الدقيق في الخشب والألواح، مع نظام أمان متطور.",
    specs: [
      { label: "القدرة", value: "1500 وات" },
      { label: "قطر الشفرة", value: "190 مم" },
      { label: "عمق القطع", value: "65 مم" },
      { label: "السرعة", value: "5500 دورة/دقيقة" },
    ],
  },
  {
    id: "p16",
    name: "وصلات PVC متنوعة",
    price: 35,
    category: "السباكة والصرف",
    brand: "بترو ست",
    rating: 4.5,
    unit: "طقم",
    description: "طقم وصلات PVC متنوع المقاسات والأشكال، مناسب لشبكات الصرف الصحي.",
    specs: [
      { label: "عدد القطع", value: "20 قطعة" },
      { label: "المقاسات", value: "32-110 مم" },
      { label: "النوع", value: "PVC-U" },
      { label: "المعيار", value: "EN 1329" },
    ],
  },
  {
    id: "p17",
    name: "نظارات حماية شفافة",
    price: 25,
    category: "السلامة المهنية",
    brand: "3M",
    rating: 4.4,
    unit: "قطعة",
    description: "نظارات حماية شفافة مقاومة للصدمات والخدوش، مريحة للاستخدام الطويل.",
    specs: [
      { label: "المادة", value: "بولي كربونات" },
      { label: "الوزن", value: "28 جرام" },
      { label: "المعيار", value: "EN 166" },
      { label: "الحماية", value: "UV 99%" },
    ],
  },
  {
    id: "p18",
    name: "أسلاك ربط حديد 1.4 مم",
    price: 18,
    category: "معدات التسليح",
    brand: "حديد الراجحي",
    rating: 4.6,
    unit: "كجم",
    description: "أسلاك ربط مرنة لتثبيت قضبان الحديد في الأعمال الإنشائية.",
    specs: [
      { label: "القطر", value: "1.4 مم" },
      { label: "المادة", value: "حديد مجلفن" },
      { label: "اللفة", value: "كجم" },
      { label: "الاستخدام", value: "ربط حديد التسليح" },
    ],
  },
  {
    id: "p19",
    name: "بلاط بورسلين رخامي 60×60",
    price: 95,
    category: "السيراميك والبلاط",
    brand: "RAK سيراميك",
    rating: 4.9,
    badge: "الأكثر مبيعاً",
    verified: true,
    unit: "م²",
    description:
      "بلاط بورسلين فاخر بنقشة رخامية، مقاوم للخدش والانزلاق، مثالي للأرضيات الداخلية والصالات.",
    specs: [
      { label: "المقاس", value: "60×60 سم" },
      { label: "السماكة", value: "10 مم" },
      { label: "اللمعان", value: "بولش لامع" },
      { label: "الامتصاص", value: "<0.5%" },
    ],
  },
  {
    id: "p20",
    name: "سيراميك جدران مطبخ 30×60",
    price: 42,
    category: "السيراميك والبلاط",
    brand: "السعودية للسيراميك",
    rating: 4.6,
    unit: "م²",
    description:
      "سيراميك جدران بألوان عصرية، مقاوم للحرارة والبخار، مناسب للمطابخ والحمامات.",
    specs: [
      { label: "المقاس", value: "30×60 سم" },
      { label: "السماكة", value: "8 مم" },
      { label: "اللمعان", value: "لامع" },
      { label: "الاستخدام", value: "جدران داخلية" },
    ],
  },
  {
    id: "p21",
    name: "بورسلين خارجي مضاد للانزلاق 45×45",
    price: 78,
    category: "السيراميك والبلاط",
    brand: "بورسلانوزا",
    rating: 4.7,
    badge: "خارجي",
    verified: true,
    unit: "م²",
    description:
      "بلاط بورسلين مخصص للمناطق الخارجية والممرات، بسطح خشن مضاد للانزلاق ومقاوم للأملاح.",
    specs: [
      { label: "المقاس", value: "45×45 سم" },
      { label: "السماكة", value: "12 مم" },
      { label: "السطح", value: "مطفي خشن" },
      { label: "مقاومة الانزلاق", value: "R11" },
    ],
  },
  {
    id: "p22",
    name: "بلاط فسيفساء زجاجي للحمامات",
    price: 135,
    category: "السيراميك والبلاط",
    brand: "RAK سيراميك",
    rating: 4.8,
    badge: "تشطيب فاخر",
    unit: "م²",
    description:
      "ألواح فسيفساء زجاجية بألوان متدرجة، تضيف لمسة فاخرة لجدران الحمامات والمطابخ المفتوحة.",
    specs: [
      { label: "حجم القطعة", value: "2.5×2.5 سم" },
      { label: "حجم اللوح", value: "30×30 سم" },
      { label: "المادة", value: "زجاج عالي الجودة" },
      { label: "الاستخدام", value: "ديكور جدران" },
    ],
  },
  // ---------- Solar panels ----------
  {
    id: "sp-panel-550",
    name: "لوح شمسي مونوكريستال 550 وات",
    price: 520,
    category: "الطاقة الشمسية",
    brand: "JA Solar",
    rating: 4.7,
    verified: true,
    unit: "لوح",
    description:
      "لوح شمسي مونوكريستال نصف خلية بقدرة 550 وات، كفاءة عالية وأداء ممتاز في درجات الحرارة المرتفعة.",
    specs: [
      { label: "القدرة", value: "550 وات" },
      { label: "الجهد (Vmp)", value: "41.8V" },
      { label: "الكفاءة", value: "21.3%" },
      { label: "الضمان", value: "25 سنة أداء" },
    ],
  },
  {
    id: "sp-panel-650",
    name: "لوح شمسي مونوكريستال 650 وات",
    price: 620,
    category: "الطاقة الشمسية",
    brand: "JA Solar",
    rating: 4.8,
    badge: "الأكثر مبيعاً",
    verified: true,
    unit: "لوح",
    description:
      "لوح شمسي بقدرة 650 وات بتقنية Mono PERC، الخيار الأمثل للأجواء الحارة والرطبة.",
    specs: [
      { label: "القدرة", value: "650 وات" },
      { label: "الجهد (Vmp)", value: "44.5V" },
      { label: "الكفاءة", value: "22.1%" },
      { label: "الضمان", value: "25 سنة أداء" },
    ],
  },
  {
    id: "sp-panel-750",
    name: "لوح شمسي مونوكريستال 750 وات",
    price: 740,
    category: "الطاقة الشمسية",
    brand: "JA Solar",
    rating: 4.9,
    badge: "قدرة عالية",
    verified: true,
    unit: "لوح",
    description:
      "لوح شمسي عالي القدرة 750 وات للمشاريع الكبيرة والعمائر السكنية، إنتاجية أعلى لكل متر مربع.",
    specs: [
      { label: "القدرة", value: "750 وات" },
      { label: "الجهد (Vmp)", value: "47.2V" },
      { label: "الكفاءة", value: "22.8%" },
      { label: "الضمان", value: "25 سنة أداء" },
    ],
  },
  // ---------- Lithium batteries ----------
  {
    id: "sp-batt-5",
    name: "بطارية ليثيوم LiFePO4 - 5 kWh",
    price: 7500,
    category: "الطاقة الشمسية",
    brand: "Pylontech",
    rating: 4.8,
    verified: true,
    unit: "وحدة",
    description:
      "بطارية ليثيوم فوسفات حديد بسعة 5 كيلوواط ساعة، آمنة ومتينة بعمر تشغيلي يتجاوز 6000 دورة شحن.",
    specs: [
      { label: "السعة", value: "5 kWh" },
      { label: "الجهد", value: "48V" },
      { label: "عمر الدورات", value: "6000+" },
      { label: "BMS", value: "ذكي مدمج" },
    ],
  },
  {
    id: "sp-batt-10",
    name: "بطارية ليثيوم LiFePO4 - 10 kWh",
    price: 14000,
    category: "الطاقة الشمسية",
    brand: "Pylontech",
    rating: 4.9,
    badge: "موصى به",
    verified: true,
    unit: "وحدة",
    description:
      "بطارية ليثيوم 10 كيلوواط ساعة مناسبة للاستخدام الليلي للشقق المتوسطة والكبيرة.",
    specs: [
      { label: "السعة", value: "10 kWh" },
      { label: "الجهد", value: "48V" },
      { label: "عمر الدورات", value: "6000+" },
      { label: "DOD", value: "90%" },
    ],
  },
  {
    id: "sp-batt-15",
    name: "بطارية ليثيوم LiFePO4 - 15 kWh",
    price: 20000,
    category: "الطاقة الشمسية",
    brand: "Pylontech",
    rating: 4.9,
    badge: "سعة كبيرة",
    verified: true,
    unit: "وحدة",
    description:
      "بنك بطاريات ليثيوم 15 كيلوواط ساعة للعمائر السكنية والمشاريع متعددة الشقق.",
    specs: [
      { label: "السعة", value: "15 kWh" },
      { label: "الجهد", value: "48V" },
      { label: "عمر الدورات", value: "6000+" },
      { label: "DOD", value: "90%" },
    ],
  },
  // ---------- Inverters ----------
  {
    id: "sp-inv-2",
    name: "محول طاقة هايبرد 2 kVA",
    price: 2200,
    category: "الطاقة الشمسية",
    brand: "Deye",
    rating: 4.6,
    verified: true,
    unit: "قطعة",
    description:
      "إنفرتر هايبرد بقدرة 2 كيلوواط مناسب للشقق الصغيرة والاستخدام المحدود.",
    specs: [
      { label: "القدرة", value: "2 kVA" },
      { label: "النوع", value: "هايبرد" },
      { label: "MPPT", value: "1 قناة" },
      { label: "الكفاءة", value: "97%" },
    ],
  },
  {
    id: "sp-inv-5",
    name: "محول طاقة هايبرد 5 kVA",
    price: 4500,
    category: "الطاقة الشمسية",
    brand: "Deye",
    rating: 4.8,
    badge: "الأكثر مبيعاً",
    verified: true,
    unit: "قطعة",
    description:
      "إنفرتر هايبرد بقدرة 5 كيلوواط الخيار الأمثل للشقق المتوسطة والكبيرة.",
    specs: [
      { label: "القدرة", value: "5 kVA" },
      { label: "النوع", value: "هايبرد" },
      { label: "MPPT", value: "2 قناة" },
      { label: "الكفاءة", value: "97.5%" },
    ],
  },
  {
    id: "sp-inv-10",
    name: "محول طاقة هايبرد 10 kVA",
    price: 9000,
    category: "الطاقة الشمسية",
    brand: "Deye",
    rating: 4.9,
    badge: "قدرة عالية",
    verified: true,
    unit: "قطعة",
    description:
      "إنفرتر هايبرد ثلاثي الطور بقدرة 10 كيلوواط للعمائر السكنية والأحمال الكبيرة.",
    specs: [
      { label: "القدرة", value: "10 kVA" },
      { label: "النوع", value: "هايبرد ثلاثي الطور" },
      { label: "MPPT", value: "2 قناة" },
      { label: "الكفاءة", value: "98%" },
    ],
  },
];
