/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CalculatorConstructionRouteImport } from './routes/calculator-construction'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as CalculatorIndexRouteImport } from './routes/calculator.index'
import { Route as CalculatorPreferencesRouteImport } from './routes/calculator.preferences'
import { Route as CalculatorDevicesRouteImport } from './routes/calculator.devices'
import { Route as StoreSolarIndexRouteImport } from './routes/store.solar.index'
import { Route as StoreSolarProductsIndexRouteImport } from './routes/store.solar.products.index'
import { Route as StoreSolarPackagesIndexRouteImport } from './routes/store.solar.packages.index'
import { Route as StoreSolarPackagesPackageIdRouteImport } from './routes/store.solar.packages.$packageId'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorConstructionRoute = CalculatorConstructionRouteImport.update({
  id: '/calculator-construction',
  path: '/calculator-construction',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorIndexRoute = CalculatorIndexRouteImport.update({
  id: '/calculator/',
  path: '/calculator/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorPreferencesRoute = CalculatorPreferencesRouteImport.update({
  id: '/calculator/preferences',
  path: '/calculator/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorDevicesRoute = CalculatorDevicesRouteImport.update({
  id: '/calculator/devices',
  path: '/calculator/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSolarIndexRoute = StoreSolarIndexRouteImport.update({
  id: '/store/solar/',
  path: '/store/solar/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSolarProductsIndexRoute = StoreSolarProductsIndexRouteImport.update({
  id: '/store/solar/products/',
  path: '/store/solar/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSolarPackagesIndexRoute = StoreSolarPackagesIndexRouteImport.update({
  id: '/store/solar/packages/',
  path: '/store/solar/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSolarPackagesPackageIdRoute =
  StoreSolarPackagesPackageIdRouteImport.update({
    id: '/store/solar/packages/$packageId',
    path: '/store/solar/packages/$packageId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator-construction': typeof CalculatorConstructionRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/tools': typeof ToolsRoute
  '/calculator/devices': typeof CalculatorDevicesRoute
  '/calculator/preferences': typeof CalculatorPreferencesRoute
  '/calculator/': typeof CalculatorIndexRoute
  '/store/': typeof StoreIndexRoute
  '/store/solar/': typeof StoreSolarIndexRoute
  '/store/solar/packages/$packageId': typeof StoreSolarPackagesPackageIdRoute
  '/store/solar/packages/': typeof StoreSolarPackagesIndexRoute
  '/store/solar/products/': typeof StoreSolarProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator-construction': typeof CalculatorConstructionRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/tools': typeof ToolsRoute
  '/calculator/devices': typeof CalculatorDevicesRoute
  '/calculator/preferences': typeof CalculatorPreferencesRoute
  '/calculator': typeof CalculatorIndexRoute
  '/store': typeof StoreIndexRoute
  '/store/solar': typeof StoreSolarIndexRoute
  '/store/solar/packages/$packageId': typeof StoreSolarPackagesPackageIdRoute
  '/store/solar/packages': typeof StoreSolarPackagesIndexRoute
  '/store/solar/products': typeof StoreSolarProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator-construction': typeof CalculatorConstructionRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/tools': typeof ToolsRoute
  '/calculator/devices': typeof CalculatorDevicesRoute
  '/calculator/preferences': typeof CalculatorPreferencesRoute
  '/calculator/': typeof CalculatorIndexRoute
  '/store/': typeof StoreIndexRoute
  '/store/solar/': typeof StoreSolarIndexRoute
  '/store/solar/packages/$packageId': typeof StoreSolarPackagesPackageIdRoute
  '/store/solar/packages/': typeof StoreSolarPackagesIndexRoute
  '/store/solar/products/': typeof StoreSolarProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator-construction'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/results'
    | '/tools'
    | '/calculator/devices'
    | '/calculator/preferences'
    | '/calculator/'
    | '/store/'
    | '/store/solar/'
    | '/store/solar/packages/$packageId'
    | '/store/solar/packages/'
    | '/store/solar/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator-construction'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/results'
    | '/tools'
    | '/calculator/devices'
    | '/calculator/preferences'
    | '/calculator'
    | '/store'
    | '/store/solar'
    | '/store/solar/packages/$packageId'
    | '/store/solar/packages'
    | '/store/solar/products'
  id:
    | '__root__'
    | '/'
    | '/calculator-construction'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/results'
    | '/tools'
    | '/calculator/devices'
    | '/calculator/preferences'
    | '/calculator/'
    | '/store/'
    | '/store/solar/'
    | '/store/solar/packages/$packageId'
    | '/store/solar/packages/'
    | '/store/solar/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorConstructionRoute: typeof CalculatorConstructionRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResultsRoute: typeof ResultsRoute
  ToolsRoute: typeof ToolsRoute
  CalculatorDevicesRoute: typeof CalculatorDevicesRoute
  CalculatorPreferencesRoute: typeof CalculatorPreferencesRoute
  CalculatorIndexRoute: typeof CalculatorIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreSolarIndexRoute: typeof StoreSolarIndexRoute
  StoreSolarPackagesPackageIdRoute: typeof StoreSolarPackagesPackageIdRoute
  StoreSolarPackagesIndexRoute: typeof StoreSolarPackagesIndexRoute
  StoreSolarProductsIndexRoute: typeof StoreSolarProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator-construction': {
      id: '/calculator-construction'
      path: '/calculator-construction'
      fullPath: '/calculator-construction'
      preLoaderRoute: typeof CalculatorConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/': {
      id: '/calculator/'
      path: '/calculator'
      fullPath: '/calculator/'
      preLoaderRoute: typeof CalculatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/preferences': {
      id: '/calculator/preferences'
      path: '/calculator/preferences'
      fullPath: '/calculator/preferences'
      preLoaderRoute: typeof CalculatorPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/devices': {
      id: '/calculator/devices'
      path: '/calculator/devices'
      fullPath: '/calculator/devices'
      preLoaderRoute: typeof CalculatorDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/solar/': {
      id: '/store/solar/'
      path: '/store/solar'
      fullPath: '/store/solar/'
      preLoaderRoute: typeof StoreSolarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/solar/products/': {
      id: '/store/solar/products/'
      path: '/store/solar/products'
      fullPath: '/store/solar/products/'
      preLoaderRoute: typeof StoreSolarProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/solar/packages/': {
      id: '/store/solar/packages/'
      path: '/store/solar/packages'
      fullPath: '/store/solar/packages/'
      preLoaderRoute: typeof StoreSolarPackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/solar/packages/$packageId': {
      id: '/store/solar/packages/$packageId'
      path: '/store/solar/packages/$packageId'
      fullPath: '/store/solar/packages/$packageId'
      preLoaderRoute: typeof StoreSolarPackagesPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorConstructionRoute: CalculatorConstructionRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResultsRoute: ResultsRoute,
  ToolsRoute: ToolsRoute,
  CalculatorDevicesRoute: CalculatorDevicesRoute,
  CalculatorPreferencesRoute: CalculatorPreferencesRoute,
  CalculatorIndexRoute: CalculatorIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreSolarIndexRoute: StoreSolarIndexRoute,
  StoreSolarPackagesPackageIdRoute: StoreSolarPackagesPackageIdRoute,
  StoreSolarPackagesIndexRoute: StoreSolarPackagesIndexRoute,
  StoreSolarProductsIndexRoute: StoreSolarProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
